#!/bin/sh

bspc config border_width          10
bspc config border_radius         10
bspc config focused_border_color  '#8fbcbb'
bspc config active_border_color   '#2e3440'
bspc config normal_border_color   '#2e3440'

bspc config top_padding           60
bspc config window_gap            20
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config split_ratio           0.52
bspc config focus_follows_pointer true

bspc config external_rules_command "/home/leon/.config/bspwm/rules"
